INSERT INTO unlocks (name, level, id_skill, other_requirement)  VALUES
('Bronze', 1, 1, 'None.[1]'),
('Iron', 1, 1, 'None.[1]'),
('Machetes', 1, 1, 'None.'),
('Steel', 5, 1, 'None.[1]'),
('Black', 10, 1, 'None.[1]'),
('White', 10, 1, 'Completion of the Wanted! quest.'),
('Ancient mace', 15, 1, ' 25  and partial completion of Another Slice of H.A.M.'),
('Mithril', 20, 1, 'None.[1]'),
('Adamant', 30, 1, 'None.[1]'),
('Battlestaves', 30, 1, ' 30 '),
('Swamp lizard', 30, 1, ' 30   30 '),
('Brine sabre', 40, 1, 'None.'),
('Mystic staves', 40, 1, ' 40 '),
('Rune', 40, 1, 'None.[1]'),
('Void knight mace', 42, 1, ' 42 , , , , , , and  22 '),
('Ancient staff', 50, 1, ' 50  and completion of Desert Treasure I.'),
('Granite maul', 50, 1, ' 50 '),
('Iban''s staff', 50, 1, ' 50  and completion of Underground Pass.'),
('Leaf-bladed spear', 50, 1, ' 55 '),
('Leaf-bladed sword', 50, 1, ' 55 '),
('Orange salamander', 50, 1, ' 50   50 '),
('Sulphur blades', 55, 1, 'None.'),
('Barrelchest anchor', 60, 1, ' 40  and completion of Great Brain Robbery.'),
('Dragon', 60, 1, 'The dragon longsword and dragon dagger require completion of the Lost City quest.The dragon mace and dragon battleaxe require completion of the Heroes'' Quest.The dragon halberd requires completion of Regicide.[1]The dragon scimitar requires completion of Monkey Madness I.'),
('Obsidian', 60, 1, 'The Obsidian maul (Tzhaar-ket-om) instead requires  60 , with no attack requirement.The Obsidian staff also requires  60 '),
('Red salamander', 60, 1, ' 60   60 '),
('Viggora''s chainmace', 60, 1, 'None.'),
('3rd age longsword', 65, 1, 'None.'),
('Keris partisan', 65, 1, 'Completion of Beneath Cursed Sands.'),
('Leaf-bladed battleaxe', 65, 1, ' 55 '),
('Sarachnis cudgel', 65, 1, 'None.'),
('Zombie axe', 65, 1, 'None.'),
('Abyssal bludgeon', 70, 1, ' 70 '),
('Abyssal dagger', 70, 1, 'None.'),
('Abyssal whip', 70, 1, 'None.'),
('Avernic defender', 70, 1, ' 70 '),
('Barrows', 70, 1, ' 70  for Dharok''s greataxe and Torag''s hammers. 70  for Ahrim''s staff.'),
('Black salamander', 70, 1, ' 70   70 '),
('Blue moon spear', 70, 1, ' 75 '),
('Dual macuahuitl', 70, 1, ' 75 '),
('Saradomin sword', 70, 1, 'None.'),
('Ursine chainmace', 70, 1, 'None.'),
('Zamorakian spear (Hasta)', 70, 1, 'None.'),
('Abyssal tentacle', 75, 1, 'None.'),
('Arclight', 75, 1, 'Completion of Shadow of the Storm.'),
('Elder maul', 75, 1, ' 75 '),
('Godswords', 75, 1, 'None.'),
('Saradomin''s blessed sword', 75, 1, 'None.'),
('Staff of the dead', 75, 1, ' 75 '),
('Voidwaker', 75, 1, 'None.'),
('Dragon hunter lance', 78, 1, 'Barbarian firemaking (excl. pyre step), fishing and smithing training.'),
('Blade of Saeldor', 80, 1, 'None.'),
('Ghrazi rapier', 80, 1, 'None.'),
('Inquisitor''s mace', 80, 1, 'None.'),
('Keris partisan of breaching (corruption) (the sun)', 80, 1, 'Completion of Tombs of Amascut.'),
('Scythe of vitur', 80, 1, ' 90 '),
('Tecu salamander', 80, 1, ' 80   80 '),
('Osmumten''s fang', 82, 1, 'None.'),
('Bronze warhammer',  1 , 2, ''),
('Iron warhammer',  1 , 2, ''),
('Steel warhammer',  5 , 2, ''),
('Black warhammer',  10 , 2, ''),
('White warhammer',  10 , 2, ''),
('Mithril warhammer',  20 , 2, ''),
('Adamant warhammer',  30 , 2, ''),
('Rune warhammer',  40 , 2, ''),
('Dragon warhammer',  60 , 2, ''),
('Black halberd',  5 , 2, ' 10 '),
('White halberd',  5 , 2, ' 10 '),
('Mithril halberd',  10 , 2, ' 20 '),
('Adamant halberd',  15 , 2, ' 30 '),
('Rune halberd',  20 , 2, ' 40 '),
('Dragon halberd',  30 , 2, ' 60 '),
('Crystal halberd',  35 , 2, ' 70  50 '),
('Barrelchest anchor',  40 , 2, ' 60 '),
('Granite maul',  50 , 2, ' 50 '),
('Granite armour',  50 , 2, ' 50 '),
('Tzhaar-ket-om',  60 , 2, ''),
('Dharok''s greataxe',  70 , 2, ' 70 '),
('Torag''s hammers',  70 , 2, ' 70 '),
('Abyssal bludgeon',  70 , 2, ' 70 '),
('Elder maul',  75 , 2, ' 75 '),
('Soulreaper axe',  80 , 2, ' 80 '),
('Scythe of vitur',  90 , 2, ' 80 '),
('Thick Skin', 1, 3, '+5% Defence'),
('Burst of Strength', 4, 3, '+5% Strength'),
('Clarity of Thought', 7, 3, '+5% Attack'),
('Sharp Eye', 8, 3, '+5% Ranged'),
('Mystic Will', 9, 3, '+5% Magic Attack and Defence'),
('Rock Skin', 10, 3, '+10% Defence'),
('Superhuman Strength', 13, 3, '+10% Strength'),
('Improved Reflexes', 16, 3, '+10% Attack'),
('Rapid Restore', 19, 3, '2x restore rate for all skills, except Hitpoints and Prayer'),
('Rapid Heal', 22, 3, '2x Restore rate for Hitpoints'),
('Protect Item', 25, 3, 'Keep one extra item upon death'),
('Hawk Eye', 26, 3, '+10% Ranged'),
('Mystic Lore', 27, 3, '+10% Magic Attack and Defence. +1% Magic damage'),
('Steel Skin', 28, 3, '+15% Defence'),
('Ultimate Strength', 31, 3, '+15% Strength'),
('Incredible Reflexes', 34, 3, '+15% Attack'),
('Protect from Magic', 37, 3, '100% protection from magic attacks by NPCs, 40% from players'),
('Protect from Missiles', 40, 3, '100% protection from ranged attacks by NPCs, 40% from players'),
('Protect from Melee', 43, 3, '100% protection from melee attacks by NPCs, 40% from players'),
('Eagle Eye', 44, 3, '+15% Ranged'),
('Mystic Might', 45, 3, '+15% Magic Attack and Defence. +2% Magic damage'),
('Retribution', 46, 3, 'Upon death, deals damage up to 25% of the player''s base Prayer level to targets in a 3x3 radius'),
('Redemption', 49, 3, 'Heals the player by 25% of their base Prayer level if they fall below 10% health, draining their prayer points fully'),
('Smite', 52, 3, 'Reduces the opponent''s prayer points by 25% of damage dealt'),
('Preserve', 55, 3, 'Boosted stats last 50% longer'),
('Chivalry', 60, 3, '+15% Attack, +18% Strength, and +20% Defence'),
('Piety', 70, 3, '+20% Attack, +23% Strength, and +25% Defence'),
('Rigour', 74, 3, '+20% Ranged attack, +23% Ranged Strength, and +25% Defence'),
('Augury', 77, 3, '+25% Magic Attack and Defence, +25% Defence. +4% magic damage'),
('Air', 1, 4, 'Normal/Pure'),
('Mind', 2, 4, 'Normal/Pure'),
('Water', 5, 4, 'Normal/Pure'),
('Earth', 9, 4, 'Normal/Pure'),
('Fire', 14, 4, 'Normal/Pure'),
('Body', 20, 4, 'Normal/Pure'),
('Cosmic', 27, 4, 'Pure'),
('Chaos', 35, 4, 'Pure'),
('Astral', 40, 4, 'Pure'),
('Nature', 44, 4, 'Pure'),
('Law', 54, 4, 'Pure'),
('Death', 65, 4, 'Pure'),
('Blood', 77, 4, 'Pure'),
('Blood(Kourend)', 77, 4, 'Dark'),
('Soul', 90, 4, 'Dark'),
('Wrath', 95, 4, 'Pure'),
('Raw shrimps',  1 , 5, 'None'),
('Raw karambwanji',  5 , 5, 'None'),
('Raw anchovies',  15 , 5, 'None'),
('Raw guppy',  7 , 5, ' Below Ice Mountain'),
('Raw cavefish',  20 , 5, ' Below Ice Mountain'),
('Raw tetra',  33 , 5, ' Below Ice Mountain'),
('Frog spawn',  33 , 5, 'None'),
('Raw monkfish',  62 , 5, ' Swan Song'),
('Minnow',  82 , 5, 'Show Kylie Minnow the full angler''s outfit.'),
('Raw mackerel',  16 , 5, 'None'),
('Raw cod',  23 , 5, 'None'),
('Raw bass',  46 , 5, 'None'),
('Raw catfish',  46 , 5, ' Below Ice Mountain'),
('Fish shoal',  47 , 5, ' 44  see drift net fishing.'),
('Raw sardine',  5 , 5, 'None'),
('Raw herring',  10 , 5, 'None'),
('Raw pike',  25 , 5, 'None'),
('Raw slimy eel',  28 , 5, 'None'),
('Raw cave eel',  38 , 5, 'None'),
('Raw anglerfish',  82 , 5, 'None'),
('Sacred eel',  87 , 5, 'Partial completion of  Regicide.'),
('Raw trout',  20 , 5, 'None'),
('Raw salmon',  30 , 5, 'None'),
('Raw rainbow fish',  38 , 5, 'None'),
('Raw lava eel',  53 , 5, 'None'),
('Infernal eel',  80 , 5, 'None'),
('Leaping trout',  48 , 5, 'None'),
('Leaping salmon',  58 , 5, 'None'),
('Leaping sturgeon',  70 , 5, 'None'),
('Raw tuna',  35 , 5, 'None'),
('Raw swordfish',  50 , 5, 'None'),
('Raw shark',  76 , 5, 'Optional:   96 ,  70 , Barbarian Training to catch without a harpoon.'),
('Raw lobster',  40 , 5, 'None'),
('Raw dark crab',  85 , 5, 'None'),
('Bluegill',  43 , 5, 'None'),
('Common tench',  56 , 5, 'None'),
('Mottled eel',  73 , 5, 'None'),
('Greater siren',  91 , 5, 'None'),
('Raw karambwan',  65 , 5, 'Completion of Tai Bwo Wannai Trio.');
