// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "is_member", Type: field.TypeInt},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
	}
	// UnlocksColumns holds the columns for the "unlocks" table.
	UnlocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "other_requirement", Type: field.TypeString},
		{Name: "level", Type: field.TypeInt},
		{Name: "id_skill", Type: field.TypeInt, Nullable: true},
	}
	// UnlocksTable holds the schema information for the "unlocks" table.
	UnlocksTable = &schema.Table{
		Name:       "unlocks",
		Columns:    UnlocksColumns,
		PrimaryKey: []*schema.Column{UnlocksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "unlocks_skills_unlocks",
				Columns:    []*schema.Column{UnlocksColumns[5]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SkillsTable,
		UnlocksTable,
	}
)

func init() {
	UnlocksTable.ForeignKeys[0].RefTable = SkillsTable
}
