// Code generated by ent, DO NOT EDIT.

package skill

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the skill type in the database.
	Label = "skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIsMember holds the string denoting the is_member field in the database.
	FieldIsMember = "is_member"
	// EdgeUnlocks holds the string denoting the unlocks edge name in mutations.
	EdgeUnlocks = "unlocks"
	// Table holds the table name of the skill in the database.
	Table = "skills"
	// UnlocksTable is the table that holds the unlocks relation/edge.
	UnlocksTable = "unlocks"
	// UnlocksInverseTable is the table name for the Unlock entity.
	// It exists in this package in order to avoid circular dependency with the "unlock" package.
	UnlocksInverseTable = "unlocks"
	// UnlocksColumn is the table column denoting the unlocks relation/edge.
	UnlocksColumn = "id_skill"
)

// Columns holds all SQL columns for skill fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldIsMember,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Skill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIsMember orders the results by the is_member field.
func ByIsMember(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsMember, opts...).ToFunc()
}

// ByUnlocksCount orders the results by unlocks count.
func ByUnlocksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUnlocksStep(), opts...)
	}
}

// ByUnlocks orders the results by unlocks terms.
func ByUnlocks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnlocksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUnlocksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnlocksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UnlocksTable, UnlocksColumn),
	)
}
