// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"runescape_http_server/ent/predicate"
	"runescape_http_server/ent/skill"
	"runescape_http_server/ent/unlock"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSkill  = "Skill"
	TypeUnlock = "Unlock"
)

// SkillMutation represents an operation that mutates the Skill nodes in the graph.
type SkillMutation struct {
	config
	op             Op
	typ            string
	id             *int
	name           *string
	description    *string
	is_member      *int
	addis_member   *int
	clearedFields  map[string]struct{}
	unlocks        map[int]struct{}
	removedunlocks map[int]struct{}
	clearedunlocks bool
	done           bool
	oldValue       func(context.Context) (*Skill, error)
	predicates     []predicate.Skill
}

var _ ent.Mutation = (*SkillMutation)(nil)

// skillOption allows management of the mutation configuration using functional options.
type skillOption func(*SkillMutation)

// newSkillMutation creates new mutation for the Skill entity.
func newSkillMutation(c config, op Op, opts ...skillOption) *SkillMutation {
	m := &SkillMutation{
		config:        c,
		op:            op,
		typ:           TypeSkill,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSkillID sets the ID field of the mutation.
func withSkillID(id int) skillOption {
	return func(m *SkillMutation) {
		var (
			err   error
			once  sync.Once
			value *Skill
		)
		m.oldValue = func(ctx context.Context) (*Skill, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Skill.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSkill sets the old Skill of the mutation.
func withSkill(node *Skill) skillOption {
	return func(m *SkillMutation) {
		m.oldValue = func(context.Context) (*Skill, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SkillMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SkillMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SkillMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SkillMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Skill.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SkillMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SkillMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Skill entity.
// If the Skill object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SkillMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SkillMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *SkillMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *SkillMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Skill entity.
// If the Skill object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SkillMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *SkillMutation) ResetDescription() {
	m.description = nil
}

// SetIsMember sets the "is_member" field.
func (m *SkillMutation) SetIsMember(i int) {
	m.is_member = &i
	m.addis_member = nil
}

// IsMember returns the value of the "is_member" field in the mutation.
func (m *SkillMutation) IsMember() (r int, exists bool) {
	v := m.is_member
	if v == nil {
		return
	}
	return *v, true
}

// OldIsMember returns the old "is_member" field's value of the Skill entity.
// If the Skill object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SkillMutation) OldIsMember(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsMember is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsMember requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsMember: %w", err)
	}
	return oldValue.IsMember, nil
}

// AddIsMember adds i to the "is_member" field.
func (m *SkillMutation) AddIsMember(i int) {
	if m.addis_member != nil {
		*m.addis_member += i
	} else {
		m.addis_member = &i
	}
}

// AddedIsMember returns the value that was added to the "is_member" field in this mutation.
func (m *SkillMutation) AddedIsMember() (r int, exists bool) {
	v := m.addis_member
	if v == nil {
		return
	}
	return *v, true
}

// ResetIsMember resets all changes to the "is_member" field.
func (m *SkillMutation) ResetIsMember() {
	m.is_member = nil
	m.addis_member = nil
}

// AddUnlockIDs adds the "unlocks" edge to the Unlock entity by ids.
func (m *SkillMutation) AddUnlockIDs(ids ...int) {
	if m.unlocks == nil {
		m.unlocks = make(map[int]struct{})
	}
	for i := range ids {
		m.unlocks[ids[i]] = struct{}{}
	}
}

// ClearUnlocks clears the "unlocks" edge to the Unlock entity.
func (m *SkillMutation) ClearUnlocks() {
	m.clearedunlocks = true
}

// UnlocksCleared reports if the "unlocks" edge to the Unlock entity was cleared.
func (m *SkillMutation) UnlocksCleared() bool {
	return m.clearedunlocks
}

// RemoveUnlockIDs removes the "unlocks" edge to the Unlock entity by IDs.
func (m *SkillMutation) RemoveUnlockIDs(ids ...int) {
	if m.removedunlocks == nil {
		m.removedunlocks = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.unlocks, ids[i])
		m.removedunlocks[ids[i]] = struct{}{}
	}
}

// RemovedUnlocks returns the removed IDs of the "unlocks" edge to the Unlock entity.
func (m *SkillMutation) RemovedUnlocksIDs() (ids []int) {
	for id := range m.removedunlocks {
		ids = append(ids, id)
	}
	return
}

// UnlocksIDs returns the "unlocks" edge IDs in the mutation.
func (m *SkillMutation) UnlocksIDs() (ids []int) {
	for id := range m.unlocks {
		ids = append(ids, id)
	}
	return
}

// ResetUnlocks resets all changes to the "unlocks" edge.
func (m *SkillMutation) ResetUnlocks() {
	m.unlocks = nil
	m.clearedunlocks = false
	m.removedunlocks = nil
}

// Where appends a list predicates to the SkillMutation builder.
func (m *SkillMutation) Where(ps ...predicate.Skill) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SkillMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SkillMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Skill, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SkillMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SkillMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Skill).
func (m *SkillMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SkillMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, skill.FieldName)
	}
	if m.description != nil {
		fields = append(fields, skill.FieldDescription)
	}
	if m.is_member != nil {
		fields = append(fields, skill.FieldIsMember)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SkillMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case skill.FieldName:
		return m.Name()
	case skill.FieldDescription:
		return m.Description()
	case skill.FieldIsMember:
		return m.IsMember()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SkillMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case skill.FieldName:
		return m.OldName(ctx)
	case skill.FieldDescription:
		return m.OldDescription(ctx)
	case skill.FieldIsMember:
		return m.OldIsMember(ctx)
	}
	return nil, fmt.Errorf("unknown Skill field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SkillMutation) SetField(name string, value ent.Value) error {
	switch name {
	case skill.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case skill.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case skill.FieldIsMember:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsMember(v)
		return nil
	}
	return fmt.Errorf("unknown Skill field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SkillMutation) AddedFields() []string {
	var fields []string
	if m.addis_member != nil {
		fields = append(fields, skill.FieldIsMember)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SkillMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case skill.FieldIsMember:
		return m.AddedIsMember()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SkillMutation) AddField(name string, value ent.Value) error {
	switch name {
	case skill.FieldIsMember:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddIsMember(v)
		return nil
	}
	return fmt.Errorf("unknown Skill numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SkillMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SkillMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SkillMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Skill nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SkillMutation) ResetField(name string) error {
	switch name {
	case skill.FieldName:
		m.ResetName()
		return nil
	case skill.FieldDescription:
		m.ResetDescription()
		return nil
	case skill.FieldIsMember:
		m.ResetIsMember()
		return nil
	}
	return fmt.Errorf("unknown Skill field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SkillMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.unlocks != nil {
		edges = append(edges, skill.EdgeUnlocks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SkillMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case skill.EdgeUnlocks:
		ids := make([]ent.Value, 0, len(m.unlocks))
		for id := range m.unlocks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SkillMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedunlocks != nil {
		edges = append(edges, skill.EdgeUnlocks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SkillMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case skill.EdgeUnlocks:
		ids := make([]ent.Value, 0, len(m.removedunlocks))
		for id := range m.removedunlocks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SkillMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedunlocks {
		edges = append(edges, skill.EdgeUnlocks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SkillMutation) EdgeCleared(name string) bool {
	switch name {
	case skill.EdgeUnlocks:
		return m.clearedunlocks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SkillMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Skill unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SkillMutation) ResetEdge(name string) error {
	switch name {
	case skill.EdgeUnlocks:
		m.ResetUnlocks()
		return nil
	}
	return fmt.Errorf("unknown Skill edge %s", name)
}

// UnlockMutation represents an operation that mutates the Unlock nodes in the graph.
type UnlockMutation struct {
	config
	op                        Op
	typ                       string
	id                        *int
	name                      *string
	description               *string
	other_requirement         *string
	level                     *int
	addlevel                  *int
	clearedFields             map[string]struct{}
	unlock_id_skill_fk        *int
	clearedunlock_id_skill_fk bool
	done                      bool
	oldValue                  func(context.Context) (*Unlock, error)
	predicates                []predicate.Unlock
}

var _ ent.Mutation = (*UnlockMutation)(nil)

// unlockOption allows management of the mutation configuration using functional options.
type unlockOption func(*UnlockMutation)

// newUnlockMutation creates new mutation for the Unlock entity.
func newUnlockMutation(c config, op Op, opts ...unlockOption) *UnlockMutation {
	m := &UnlockMutation{
		config:        c,
		op:            op,
		typ:           TypeUnlock,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUnlockID sets the ID field of the mutation.
func withUnlockID(id int) unlockOption {
	return func(m *UnlockMutation) {
		var (
			err   error
			once  sync.Once
			value *Unlock
		)
		m.oldValue = func(ctx context.Context) (*Unlock, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Unlock.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUnlock sets the old Unlock of the mutation.
func withUnlock(node *Unlock) unlockOption {
	return func(m *UnlockMutation) {
		m.oldValue = func(context.Context) (*Unlock, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UnlockMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UnlockMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UnlockMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UnlockMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Unlock.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetIDSkill sets the "id_skill" field.
func (m *UnlockMutation) SetIDSkill(i int) {
	m.unlock_id_skill_fk = &i
}

// IDSkill returns the value of the "id_skill" field in the mutation.
func (m *UnlockMutation) IDSkill() (r int, exists bool) {
	v := m.unlock_id_skill_fk
	if v == nil {
		return
	}
	return *v, true
}

// OldIDSkill returns the old "id_skill" field's value of the Unlock entity.
// If the Unlock object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UnlockMutation) OldIDSkill(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIDSkill is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIDSkill requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIDSkill: %w", err)
	}
	return oldValue.IDSkill, nil
}

// ClearIDSkill clears the value of the "id_skill" field.
func (m *UnlockMutation) ClearIDSkill() {
	m.unlock_id_skill_fk = nil
	m.clearedFields[unlock.FieldIDSkill] = struct{}{}
}

// IDSkillCleared returns if the "id_skill" field was cleared in this mutation.
func (m *UnlockMutation) IDSkillCleared() bool {
	_, ok := m.clearedFields[unlock.FieldIDSkill]
	return ok
}

// ResetIDSkill resets all changes to the "id_skill" field.
func (m *UnlockMutation) ResetIDSkill() {
	m.unlock_id_skill_fk = nil
	delete(m.clearedFields, unlock.FieldIDSkill)
}

// SetName sets the "name" field.
func (m *UnlockMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UnlockMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Unlock entity.
// If the Unlock object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UnlockMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UnlockMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *UnlockMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *UnlockMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Unlock entity.
// If the Unlock object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UnlockMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *UnlockMutation) ResetDescription() {
	m.description = nil
}

// SetOtherRequirement sets the "other_requirement" field.
func (m *UnlockMutation) SetOtherRequirement(s string) {
	m.other_requirement = &s
}

// OtherRequirement returns the value of the "other_requirement" field in the mutation.
func (m *UnlockMutation) OtherRequirement() (r string, exists bool) {
	v := m.other_requirement
	if v == nil {
		return
	}
	return *v, true
}

// OldOtherRequirement returns the old "other_requirement" field's value of the Unlock entity.
// If the Unlock object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UnlockMutation) OldOtherRequirement(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOtherRequirement is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOtherRequirement requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOtherRequirement: %w", err)
	}
	return oldValue.OtherRequirement, nil
}

// ResetOtherRequirement resets all changes to the "other_requirement" field.
func (m *UnlockMutation) ResetOtherRequirement() {
	m.other_requirement = nil
}

// SetLevel sets the "level" field.
func (m *UnlockMutation) SetLevel(i int) {
	m.level = &i
	m.addlevel = nil
}

// Level returns the value of the "level" field in the mutation.
func (m *UnlockMutation) Level() (r int, exists bool) {
	v := m.level
	if v == nil {
		return
	}
	return *v, true
}

// OldLevel returns the old "level" field's value of the Unlock entity.
// If the Unlock object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UnlockMutation) OldLevel(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLevel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLevel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLevel: %w", err)
	}
	return oldValue.Level, nil
}

// AddLevel adds i to the "level" field.
func (m *UnlockMutation) AddLevel(i int) {
	if m.addlevel != nil {
		*m.addlevel += i
	} else {
		m.addlevel = &i
	}
}

// AddedLevel returns the value that was added to the "level" field in this mutation.
func (m *UnlockMutation) AddedLevel() (r int, exists bool) {
	v := m.addlevel
	if v == nil {
		return
	}
	return *v, true
}

// ResetLevel resets all changes to the "level" field.
func (m *UnlockMutation) ResetLevel() {
	m.level = nil
	m.addlevel = nil
}

// SetUnlockIDSkillFkID sets the "unlock_id_skill_fk" edge to the Skill entity by id.
func (m *UnlockMutation) SetUnlockIDSkillFkID(id int) {
	m.unlock_id_skill_fk = &id
}

// ClearUnlockIDSkillFk clears the "unlock_id_skill_fk" edge to the Skill entity.
func (m *UnlockMutation) ClearUnlockIDSkillFk() {
	m.clearedunlock_id_skill_fk = true
	m.clearedFields[unlock.FieldIDSkill] = struct{}{}
}

// UnlockIDSkillFkCleared reports if the "unlock_id_skill_fk" edge to the Skill entity was cleared.
func (m *UnlockMutation) UnlockIDSkillFkCleared() bool {
	return m.IDSkillCleared() || m.clearedunlock_id_skill_fk
}

// UnlockIDSkillFkID returns the "unlock_id_skill_fk" edge ID in the mutation.
func (m *UnlockMutation) UnlockIDSkillFkID() (id int, exists bool) {
	if m.unlock_id_skill_fk != nil {
		return *m.unlock_id_skill_fk, true
	}
	return
}

// UnlockIDSkillFkIDs returns the "unlock_id_skill_fk" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UnlockIDSkillFkID instead. It exists only for internal usage by the builders.
func (m *UnlockMutation) UnlockIDSkillFkIDs() (ids []int) {
	if id := m.unlock_id_skill_fk; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUnlockIDSkillFk resets all changes to the "unlock_id_skill_fk" edge.
func (m *UnlockMutation) ResetUnlockIDSkillFk() {
	m.unlock_id_skill_fk = nil
	m.clearedunlock_id_skill_fk = false
}

// Where appends a list predicates to the UnlockMutation builder.
func (m *UnlockMutation) Where(ps ...predicate.Unlock) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UnlockMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UnlockMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Unlock, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UnlockMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UnlockMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Unlock).
func (m *UnlockMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UnlockMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.unlock_id_skill_fk != nil {
		fields = append(fields, unlock.FieldIDSkill)
	}
	if m.name != nil {
		fields = append(fields, unlock.FieldName)
	}
	if m.description != nil {
		fields = append(fields, unlock.FieldDescription)
	}
	if m.other_requirement != nil {
		fields = append(fields, unlock.FieldOtherRequirement)
	}
	if m.level != nil {
		fields = append(fields, unlock.FieldLevel)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UnlockMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case unlock.FieldIDSkill:
		return m.IDSkill()
	case unlock.FieldName:
		return m.Name()
	case unlock.FieldDescription:
		return m.Description()
	case unlock.FieldOtherRequirement:
		return m.OtherRequirement()
	case unlock.FieldLevel:
		return m.Level()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UnlockMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case unlock.FieldIDSkill:
		return m.OldIDSkill(ctx)
	case unlock.FieldName:
		return m.OldName(ctx)
	case unlock.FieldDescription:
		return m.OldDescription(ctx)
	case unlock.FieldOtherRequirement:
		return m.OldOtherRequirement(ctx)
	case unlock.FieldLevel:
		return m.OldLevel(ctx)
	}
	return nil, fmt.Errorf("unknown Unlock field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UnlockMutation) SetField(name string, value ent.Value) error {
	switch name {
	case unlock.FieldIDSkill:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIDSkill(v)
		return nil
	case unlock.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case unlock.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case unlock.FieldOtherRequirement:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOtherRequirement(v)
		return nil
	case unlock.FieldLevel:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLevel(v)
		return nil
	}
	return fmt.Errorf("unknown Unlock field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UnlockMutation) AddedFields() []string {
	var fields []string
	if m.addlevel != nil {
		fields = append(fields, unlock.FieldLevel)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UnlockMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case unlock.FieldLevel:
		return m.AddedLevel()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UnlockMutation) AddField(name string, value ent.Value) error {
	switch name {
	case unlock.FieldLevel:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLevel(v)
		return nil
	}
	return fmt.Errorf("unknown Unlock numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UnlockMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(unlock.FieldIDSkill) {
		fields = append(fields, unlock.FieldIDSkill)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UnlockMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UnlockMutation) ClearField(name string) error {
	switch name {
	case unlock.FieldIDSkill:
		m.ClearIDSkill()
		return nil
	}
	return fmt.Errorf("unknown Unlock nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UnlockMutation) ResetField(name string) error {
	switch name {
	case unlock.FieldIDSkill:
		m.ResetIDSkill()
		return nil
	case unlock.FieldName:
		m.ResetName()
		return nil
	case unlock.FieldDescription:
		m.ResetDescription()
		return nil
	case unlock.FieldOtherRequirement:
		m.ResetOtherRequirement()
		return nil
	case unlock.FieldLevel:
		m.ResetLevel()
		return nil
	}
	return fmt.Errorf("unknown Unlock field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UnlockMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.unlock_id_skill_fk != nil {
		edges = append(edges, unlock.EdgeUnlockIDSkillFk)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UnlockMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case unlock.EdgeUnlockIDSkillFk:
		if id := m.unlock_id_skill_fk; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UnlockMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UnlockMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UnlockMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedunlock_id_skill_fk {
		edges = append(edges, unlock.EdgeUnlockIDSkillFk)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UnlockMutation) EdgeCleared(name string) bool {
	switch name {
	case unlock.EdgeUnlockIDSkillFk:
		return m.clearedunlock_id_skill_fk
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UnlockMutation) ClearEdge(name string) error {
	switch name {
	case unlock.EdgeUnlockIDSkillFk:
		m.ClearUnlockIDSkillFk()
		return nil
	}
	return fmt.Errorf("unknown Unlock unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UnlockMutation) ResetEdge(name string) error {
	switch name {
	case unlock.EdgeUnlockIDSkillFk:
		m.ResetUnlockIDSkillFk()
		return nil
	}
	return fmt.Errorf("unknown Unlock edge %s", name)
}
