// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"runescape_http_server/ent/otherrequirement"
	"runescape_http_server/ent/predicate"
	"runescape_http_server/ent/unlock"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OtherRequirementQuery is the builder for querying OtherRequirement entities.
type OtherRequirementQuery struct {
	config
	ctx                            *QueryContext
	order                          []otherrequirement.OrderOption
	inters                         []Interceptor
	predicates                     []predicate.OtherRequirement
	withOtherRequirementIDUnlockFk *UnlockQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OtherRequirementQuery builder.
func (orq *OtherRequirementQuery) Where(ps ...predicate.OtherRequirement) *OtherRequirementQuery {
	orq.predicates = append(orq.predicates, ps...)
	return orq
}

// Limit the number of records to be returned by this query.
func (orq *OtherRequirementQuery) Limit(limit int) *OtherRequirementQuery {
	orq.ctx.Limit = &limit
	return orq
}

// Offset to start from.
func (orq *OtherRequirementQuery) Offset(offset int) *OtherRequirementQuery {
	orq.ctx.Offset = &offset
	return orq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (orq *OtherRequirementQuery) Unique(unique bool) *OtherRequirementQuery {
	orq.ctx.Unique = &unique
	return orq
}

// Order specifies how the records should be ordered.
func (orq *OtherRequirementQuery) Order(o ...otherrequirement.OrderOption) *OtherRequirementQuery {
	orq.order = append(orq.order, o...)
	return orq
}

// QueryOtherRequirementIDUnlockFk chains the current query on the "other_requirement_id_unlock_fk" edge.
func (orq *OtherRequirementQuery) QueryOtherRequirementIDUnlockFk() *UnlockQuery {
	query := (&UnlockClient{config: orq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := orq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := orq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(otherrequirement.Table, otherrequirement.FieldID, selector),
			sqlgraph.To(unlock.Table, unlock.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, otherrequirement.OtherRequirementIDUnlockFkTable, otherrequirement.OtherRequirementIDUnlockFkColumn),
		)
		fromU = sqlgraph.SetNeighbors(orq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OtherRequirement entity from the query.
// Returns a *NotFoundError when no OtherRequirement was found.
func (orq *OtherRequirementQuery) First(ctx context.Context) (*OtherRequirement, error) {
	nodes, err := orq.Limit(1).All(setContextOp(ctx, orq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{otherrequirement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (orq *OtherRequirementQuery) FirstX(ctx context.Context) *OtherRequirement {
	node, err := orq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OtherRequirement ID from the query.
// Returns a *NotFoundError when no OtherRequirement ID was found.
func (orq *OtherRequirementQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = orq.Limit(1).IDs(setContextOp(ctx, orq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{otherrequirement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (orq *OtherRequirementQuery) FirstIDX(ctx context.Context) int {
	id, err := orq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OtherRequirement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OtherRequirement entity is found.
// Returns a *NotFoundError when no OtherRequirement entities are found.
func (orq *OtherRequirementQuery) Only(ctx context.Context) (*OtherRequirement, error) {
	nodes, err := orq.Limit(2).All(setContextOp(ctx, orq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{otherrequirement.Label}
	default:
		return nil, &NotSingularError{otherrequirement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (orq *OtherRequirementQuery) OnlyX(ctx context.Context) *OtherRequirement {
	node, err := orq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OtherRequirement ID in the query.
// Returns a *NotSingularError when more than one OtherRequirement ID is found.
// Returns a *NotFoundError when no entities are found.
func (orq *OtherRequirementQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = orq.Limit(2).IDs(setContextOp(ctx, orq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{otherrequirement.Label}
	default:
		err = &NotSingularError{otherrequirement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (orq *OtherRequirementQuery) OnlyIDX(ctx context.Context) int {
	id, err := orq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OtherRequirements.
func (orq *OtherRequirementQuery) All(ctx context.Context) ([]*OtherRequirement, error) {
	ctx = setContextOp(ctx, orq.ctx, "All")
	if err := orq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OtherRequirement, *OtherRequirementQuery]()
	return withInterceptors[[]*OtherRequirement](ctx, orq, qr, orq.inters)
}

// AllX is like All, but panics if an error occurs.
func (orq *OtherRequirementQuery) AllX(ctx context.Context) []*OtherRequirement {
	nodes, err := orq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OtherRequirement IDs.
func (orq *OtherRequirementQuery) IDs(ctx context.Context) (ids []int, err error) {
	if orq.ctx.Unique == nil && orq.path != nil {
		orq.Unique(true)
	}
	ctx = setContextOp(ctx, orq.ctx, "IDs")
	if err = orq.Select(otherrequirement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (orq *OtherRequirementQuery) IDsX(ctx context.Context) []int {
	ids, err := orq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (orq *OtherRequirementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, orq.ctx, "Count")
	if err := orq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, orq, querierCount[*OtherRequirementQuery](), orq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (orq *OtherRequirementQuery) CountX(ctx context.Context) int {
	count, err := orq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (orq *OtherRequirementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, orq.ctx, "Exist")
	switch _, err := orq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (orq *OtherRequirementQuery) ExistX(ctx context.Context) bool {
	exist, err := orq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OtherRequirementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (orq *OtherRequirementQuery) Clone() *OtherRequirementQuery {
	if orq == nil {
		return nil
	}
	return &OtherRequirementQuery{
		config:                         orq.config,
		ctx:                            orq.ctx.Clone(),
		order:                          append([]otherrequirement.OrderOption{}, orq.order...),
		inters:                         append([]Interceptor{}, orq.inters...),
		predicates:                     append([]predicate.OtherRequirement{}, orq.predicates...),
		withOtherRequirementIDUnlockFk: orq.withOtherRequirementIDUnlockFk.Clone(),
		// clone intermediate query.
		sql:  orq.sql.Clone(),
		path: orq.path,
	}
}

// WithOtherRequirementIDUnlockFk tells the query-builder to eager-load the nodes that are connected to
// the "other_requirement_id_unlock_fk" edge. The optional arguments are used to configure the query builder of the edge.
func (orq *OtherRequirementQuery) WithOtherRequirementIDUnlockFk(opts ...func(*UnlockQuery)) *OtherRequirementQuery {
	query := (&UnlockClient{config: orq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	orq.withOtherRequirementIDUnlockFk = query
	return orq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OtherRequirement.Query().
//		GroupBy(otherrequirement.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (orq *OtherRequirementQuery) GroupBy(field string, fields ...string) *OtherRequirementGroupBy {
	orq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OtherRequirementGroupBy{build: orq}
	grbuild.flds = &orq.ctx.Fields
	grbuild.label = otherrequirement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name"`
//	}
//
//	client.OtherRequirement.Query().
//		Select(otherrequirement.FieldName).
//		Scan(ctx, &v)
func (orq *OtherRequirementQuery) Select(fields ...string) *OtherRequirementSelect {
	orq.ctx.Fields = append(orq.ctx.Fields, fields...)
	sbuild := &OtherRequirementSelect{OtherRequirementQuery: orq}
	sbuild.label = otherrequirement.Label
	sbuild.flds, sbuild.scan = &orq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OtherRequirementSelect configured with the given aggregations.
func (orq *OtherRequirementQuery) Aggregate(fns ...AggregateFunc) *OtherRequirementSelect {
	return orq.Select().Aggregate(fns...)
}

func (orq *OtherRequirementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range orq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, orq); err != nil {
				return err
			}
		}
	}
	for _, f := range orq.ctx.Fields {
		if !otherrequirement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if orq.path != nil {
		prev, err := orq.path(ctx)
		if err != nil {
			return err
		}
		orq.sql = prev
	}
	return nil
}

func (orq *OtherRequirementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OtherRequirement, error) {
	var (
		nodes       = []*OtherRequirement{}
		_spec       = orq.querySpec()
		loadedTypes = [1]bool{
			orq.withOtherRequirementIDUnlockFk != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OtherRequirement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OtherRequirement{config: orq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, orq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := orq.withOtherRequirementIDUnlockFk; query != nil {
		if err := orq.loadOtherRequirementIDUnlockFk(ctx, query, nodes, nil,
			func(n *OtherRequirement, e *Unlock) { n.Edges.OtherRequirementIDUnlockFk = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (orq *OtherRequirementQuery) loadOtherRequirementIDUnlockFk(ctx context.Context, query *UnlockQuery, nodes []*OtherRequirement, init func(*OtherRequirement), assign func(*OtherRequirement, *Unlock)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OtherRequirement)
	for i := range nodes {
		fk := nodes[i].IDUnlock
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(unlock.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "id_unlock" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (orq *OtherRequirementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := orq.querySpec()
	_spec.Node.Columns = orq.ctx.Fields
	if len(orq.ctx.Fields) > 0 {
		_spec.Unique = orq.ctx.Unique != nil && *orq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, orq.driver, _spec)
}

func (orq *OtherRequirementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(otherrequirement.Table, otherrequirement.Columns, sqlgraph.NewFieldSpec(otherrequirement.FieldID, field.TypeInt))
	_spec.From = orq.sql
	if unique := orq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if orq.path != nil {
		_spec.Unique = true
	}
	if fields := orq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otherrequirement.FieldID)
		for i := range fields {
			if fields[i] != otherrequirement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if orq.withOtherRequirementIDUnlockFk != nil {
			_spec.Node.AddColumnOnce(otherrequirement.FieldIDUnlock)
		}
	}
	if ps := orq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := orq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := orq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := orq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (orq *OtherRequirementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(orq.driver.Dialect())
	t1 := builder.Table(otherrequirement.Table)
	columns := orq.ctx.Fields
	if len(columns) == 0 {
		columns = otherrequirement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if orq.sql != nil {
		selector = orq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if orq.ctx.Unique != nil && *orq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range orq.predicates {
		p(selector)
	}
	for _, p := range orq.order {
		p(selector)
	}
	if offset := orq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := orq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OtherRequirementGroupBy is the group-by builder for OtherRequirement entities.
type OtherRequirementGroupBy struct {
	selector
	build *OtherRequirementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (orgb *OtherRequirementGroupBy) Aggregate(fns ...AggregateFunc) *OtherRequirementGroupBy {
	orgb.fns = append(orgb.fns, fns...)
	return orgb
}

// Scan applies the selector query and scans the result into the given value.
func (orgb *OtherRequirementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, orgb.build.ctx, "GroupBy")
	if err := orgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OtherRequirementQuery, *OtherRequirementGroupBy](ctx, orgb.build, orgb, orgb.build.inters, v)
}

func (orgb *OtherRequirementGroupBy) sqlScan(ctx context.Context, root *OtherRequirementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(orgb.fns))
	for _, fn := range orgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*orgb.flds)+len(orgb.fns))
		for _, f := range *orgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*orgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := orgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OtherRequirementSelect is the builder for selecting fields of OtherRequirement entities.
type OtherRequirementSelect struct {
	*OtherRequirementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ors *OtherRequirementSelect) Aggregate(fns ...AggregateFunc) *OtherRequirementSelect {
	ors.fns = append(ors.fns, fns...)
	return ors
}

// Scan applies the selector query and scans the result into the given value.
func (ors *OtherRequirementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ors.ctx, "Select")
	if err := ors.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OtherRequirementQuery, *OtherRequirementSelect](ctx, ors.OtherRequirementQuery, ors, ors.inters, v)
}

func (ors *OtherRequirementSelect) sqlScan(ctx context.Context, root *OtherRequirementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ors.fns))
	for _, fn := range ors.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ors.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ors.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
