// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"runescape_http_server/ent/predicate"
	"runescape_http_server/ent/unlock"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnlockDelete is the builder for deleting a Unlock entity.
type UnlockDelete struct {
	config
	hooks    []Hook
	mutation *UnlockMutation
}

// Where appends a list predicates to the UnlockDelete builder.
func (ud *UnlockDelete) Where(ps ...predicate.Unlock) *UnlockDelete {
	ud.mutation.Where(ps...)
	return ud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ud *UnlockDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ud.sqlExec, ud.mutation, ud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ud *UnlockDelete) ExecX(ctx context.Context) int {
	n, err := ud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ud *UnlockDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(unlock.Table, sqlgraph.NewFieldSpec(unlock.FieldID, field.TypeInt))
	if ps := ud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ud.mutation.done = true
	return affected, err
}

// UnlockDeleteOne is the builder for deleting a single Unlock entity.
type UnlockDeleteOne struct {
	ud *UnlockDelete
}

// Where appends a list predicates to the UnlockDelete builder.
func (udo *UnlockDeleteOne) Where(ps ...predicate.Unlock) *UnlockDeleteOne {
	udo.ud.mutation.Where(ps...)
	return udo
}

// Exec executes the deletion query.
func (udo *UnlockDeleteOne) Exec(ctx context.Context) error {
	n, err := udo.ud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{unlock.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (udo *UnlockDeleteOne) ExecX(ctx context.Context) {
	if err := udo.Exec(ctx); err != nil {
		panic(err)
	}
}
