// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"runescape_http_server/ent/predicate"
	"runescape_http_server/ent/skill"
	"runescape_http_server/ent/unlock"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnlockQuery is the builder for querying Unlock entities.
type UnlockQuery struct {
	config
	ctx                 *QueryContext
	order               []unlock.OrderOption
	inters              []Interceptor
	predicates          []predicate.Unlock
	withUnlockIDSkillFk *SkillQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UnlockQuery builder.
func (uq *UnlockQuery) Where(ps ...predicate.Unlock) *UnlockQuery {
	uq.predicates = append(uq.predicates, ps...)
	return uq
}

// Limit the number of records to be returned by this query.
func (uq *UnlockQuery) Limit(limit int) *UnlockQuery {
	uq.ctx.Limit = &limit
	return uq
}

// Offset to start from.
func (uq *UnlockQuery) Offset(offset int) *UnlockQuery {
	uq.ctx.Offset = &offset
	return uq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uq *UnlockQuery) Unique(unique bool) *UnlockQuery {
	uq.ctx.Unique = &unique
	return uq
}

// Order specifies how the records should be ordered.
func (uq *UnlockQuery) Order(o ...unlock.OrderOption) *UnlockQuery {
	uq.order = append(uq.order, o...)
	return uq
}

// QueryUnlockIDSkillFk chains the current query on the "unlock_id_skill_fk" edge.
func (uq *UnlockQuery) QueryUnlockIDSkillFk() *SkillQuery {
	query := (&SkillClient{config: uq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(unlock.Table, unlock.FieldID, selector),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, unlock.UnlockIDSkillFkTable, unlock.UnlockIDSkillFkColumn),
		)
		fromU = sqlgraph.SetNeighbors(uq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Unlock entity from the query.
// Returns a *NotFoundError when no Unlock was found.
func (uq *UnlockQuery) First(ctx context.Context) (*Unlock, error) {
	nodes, err := uq.Limit(1).All(setContextOp(ctx, uq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{unlock.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uq *UnlockQuery) FirstX(ctx context.Context) *Unlock {
	node, err := uq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Unlock ID from the query.
// Returns a *NotFoundError when no Unlock ID was found.
func (uq *UnlockQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uq.Limit(1).IDs(setContextOp(ctx, uq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{unlock.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uq *UnlockQuery) FirstIDX(ctx context.Context) int {
	id, err := uq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Unlock entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Unlock entity is found.
// Returns a *NotFoundError when no Unlock entities are found.
func (uq *UnlockQuery) Only(ctx context.Context) (*Unlock, error) {
	nodes, err := uq.Limit(2).All(setContextOp(ctx, uq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{unlock.Label}
	default:
		return nil, &NotSingularError{unlock.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uq *UnlockQuery) OnlyX(ctx context.Context) *Unlock {
	node, err := uq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Unlock ID in the query.
// Returns a *NotSingularError when more than one Unlock ID is found.
// Returns a *NotFoundError when no entities are found.
func (uq *UnlockQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uq.Limit(2).IDs(setContextOp(ctx, uq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{unlock.Label}
	default:
		err = &NotSingularError{unlock.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uq *UnlockQuery) OnlyIDX(ctx context.Context) int {
	id, err := uq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Unlocks.
func (uq *UnlockQuery) All(ctx context.Context) ([]*Unlock, error) {
	ctx = setContextOp(ctx, uq.ctx, "All")
	if err := uq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Unlock, *UnlockQuery]()
	return withInterceptors[[]*Unlock](ctx, uq, qr, uq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uq *UnlockQuery) AllX(ctx context.Context) []*Unlock {
	nodes, err := uq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Unlock IDs.
func (uq *UnlockQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uq.ctx.Unique == nil && uq.path != nil {
		uq.Unique(true)
	}
	ctx = setContextOp(ctx, uq.ctx, "IDs")
	if err = uq.Select(unlock.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uq *UnlockQuery) IDsX(ctx context.Context) []int {
	ids, err := uq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uq *UnlockQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uq.ctx, "Count")
	if err := uq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uq, querierCount[*UnlockQuery](), uq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uq *UnlockQuery) CountX(ctx context.Context) int {
	count, err := uq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uq *UnlockQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uq.ctx, "Exist")
	switch _, err := uq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uq *UnlockQuery) ExistX(ctx context.Context) bool {
	exist, err := uq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UnlockQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uq *UnlockQuery) Clone() *UnlockQuery {
	if uq == nil {
		return nil
	}
	return &UnlockQuery{
		config:              uq.config,
		ctx:                 uq.ctx.Clone(),
		order:               append([]unlock.OrderOption{}, uq.order...),
		inters:              append([]Interceptor{}, uq.inters...),
		predicates:          append([]predicate.Unlock{}, uq.predicates...),
		withUnlockIDSkillFk: uq.withUnlockIDSkillFk.Clone(),
		// clone intermediate query.
		sql:  uq.sql.Clone(),
		path: uq.path,
	}
}

// WithUnlockIDSkillFk tells the query-builder to eager-load the nodes that are connected to
// the "unlock_id_skill_fk" edge. The optional arguments are used to configure the query builder of the edge.
func (uq *UnlockQuery) WithUnlockIDSkillFk(opts ...func(*SkillQuery)) *UnlockQuery {
	query := (&SkillClient{config: uq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uq.withUnlockIDSkillFk = query
	return uq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IDSkill int `json:"idSkill"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Unlock.Query().
//		GroupBy(unlock.FieldIDSkill).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uq *UnlockQuery) GroupBy(field string, fields ...string) *UnlockGroupBy {
	uq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UnlockGroupBy{build: uq}
	grbuild.flds = &uq.ctx.Fields
	grbuild.label = unlock.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IDSkill int `json:"idSkill"`
//	}
//
//	client.Unlock.Query().
//		Select(unlock.FieldIDSkill).
//		Scan(ctx, &v)
func (uq *UnlockQuery) Select(fields ...string) *UnlockSelect {
	uq.ctx.Fields = append(uq.ctx.Fields, fields...)
	sbuild := &UnlockSelect{UnlockQuery: uq}
	sbuild.label = unlock.Label
	sbuild.flds, sbuild.scan = &uq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UnlockSelect configured with the given aggregations.
func (uq *UnlockQuery) Aggregate(fns ...AggregateFunc) *UnlockSelect {
	return uq.Select().Aggregate(fns...)
}

func (uq *UnlockQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uq); err != nil {
				return err
			}
		}
	}
	for _, f := range uq.ctx.Fields {
		if !unlock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uq.path != nil {
		prev, err := uq.path(ctx)
		if err != nil {
			return err
		}
		uq.sql = prev
	}
	return nil
}

func (uq *UnlockQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Unlock, error) {
	var (
		nodes       = []*Unlock{}
		_spec       = uq.querySpec()
		loadedTypes = [1]bool{
			uq.withUnlockIDSkillFk != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Unlock).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Unlock{config: uq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uq.withUnlockIDSkillFk; query != nil {
		if err := uq.loadUnlockIDSkillFk(ctx, query, nodes, nil,
			func(n *Unlock, e *Skill) { n.Edges.UnlockIDSkillFk = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uq *UnlockQuery) loadUnlockIDSkillFk(ctx context.Context, query *SkillQuery, nodes []*Unlock, init func(*Unlock), assign func(*Unlock, *Skill)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Unlock)
	for i := range nodes {
		fk := nodes[i].IDSkill
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(skill.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "id_skill" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uq *UnlockQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uq.querySpec()
	_spec.Node.Columns = uq.ctx.Fields
	if len(uq.ctx.Fields) > 0 {
		_spec.Unique = uq.ctx.Unique != nil && *uq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uq.driver, _spec)
}

func (uq *UnlockQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(unlock.Table, unlock.Columns, sqlgraph.NewFieldSpec(unlock.FieldID, field.TypeInt))
	_spec.From = uq.sql
	if unique := uq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uq.path != nil {
		_spec.Unique = true
	}
	if fields := uq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unlock.FieldID)
		for i := range fields {
			if fields[i] != unlock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if uq.withUnlockIDSkillFk != nil {
			_spec.Node.AddColumnOnce(unlock.FieldIDSkill)
		}
	}
	if ps := uq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uq *UnlockQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uq.driver.Dialect())
	t1 := builder.Table(unlock.Table)
	columns := uq.ctx.Fields
	if len(columns) == 0 {
		columns = unlock.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uq.sql != nil {
		selector = uq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uq.ctx.Unique != nil && *uq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uq.predicates {
		p(selector)
	}
	for _, p := range uq.order {
		p(selector)
	}
	if offset := uq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UnlockGroupBy is the group-by builder for Unlock entities.
type UnlockGroupBy struct {
	selector
	build *UnlockQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ugb *UnlockGroupBy) Aggregate(fns ...AggregateFunc) *UnlockGroupBy {
	ugb.fns = append(ugb.fns, fns...)
	return ugb
}

// Scan applies the selector query and scans the result into the given value.
func (ugb *UnlockGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ugb.build.ctx, "GroupBy")
	if err := ugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UnlockQuery, *UnlockGroupBy](ctx, ugb.build, ugb, ugb.build.inters, v)
}

func (ugb *UnlockGroupBy) sqlScan(ctx context.Context, root *UnlockQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ugb.fns))
	for _, fn := range ugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ugb.flds)+len(ugb.fns))
		for _, f := range *ugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UnlockSelect is the builder for selecting fields of Unlock entities.
type UnlockSelect struct {
	*UnlockQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (us *UnlockSelect) Aggregate(fns ...AggregateFunc) *UnlockSelect {
	us.fns = append(us.fns, fns...)
	return us
}

// Scan applies the selector query and scans the result into the given value.
func (us *UnlockSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, us.ctx, "Select")
	if err := us.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UnlockQuery, *UnlockSelect](ctx, us.UnlockQuery, us, us.inters, v)
}

func (us *UnlockSelect) sqlScan(ctx context.Context, root *UnlockQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(us.fns))
	for _, fn := range us.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*us.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := us.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
