INSERT INTO skills (name, description, is_member) VALUES 
('Attack', 'Wielding stronger melee weapons and hitting monsters more accurately in Melee.', 0),
('Strength', 'Dealing more melee damage and equipping certain weapons.', 0),
('Defence', 'Wearing stronger armour and decreasing chance of being hit.', 0),
('Ranged', 'Equipping stronger ranged weapons and armour. It also increases ranged accuracy.', 0),
('Prayer', 'Activating temporary aids to assist in combat.', 0),
('Magic', 'Casting various combat and utility spells.', 0),
('Runecraft', 'Creating runes used for casting Magic.', 0),
('Hitpoints', 'Amount of damage you can withstand.', 0),
('Crafting', 'Creating items such as jewellery, pottery, and ranged armour.', 0),
('Mining', 'Obtaining ores and minerals from rocks.', 0),
('Smithing', 'Smelting ores into bars and forging bars into armour and weapons.', 0),
('Fishing', 'Catching fish.', 0),
('Cooking', 'Making and cooking food.', 0),
('Firemaking', 'Lighting logs into fire.', 0),
('Woodcutting', 'Chopping down trees.', 0),
('Agility', 'Traversing shortcuts and increases the rate at which energy recharges.', 1),
('Herblore', 'Cleaning and using herbs to create potions.', 1),
('Thieving', 'Stealing from market stalls and chests and pickpocketing non-player characters.', 1),
('Fletching', 'Creating ranged weapons and ammunition.', 1),
('Slayer', 'Killing certain monsters that can''t normally be defeated.', 1),
('Farming', 'Planting and harvesting crops.', 1),
('Construction', 'Building a player-owned house.', 1),
('Hunter', 'Capturing wild animals and creatures.', 1);